begin;
do $$ declare r uuid; c jsonb; f jsonb:='{"synthetic":true,"required_fields":["nombre","firma"],"record":{"nombre":"EJEMPLO","firma":null},"rule":"all required fields must be nonempty","can_close":false}'::jsonb;
begin
if f#>>'{record,nombre}' is null or f#>>'{record,firma}' is not null or f->>'can_close'<>'false' then raise exception 'FIXTURE_LOGIC';end if;
insert into public.sc_fact_bank(fact_id,claim,source_url,source_title,source_kind,status,authority,confidence,scope,metadata,approved_at) values('SC-STAGING-CHECK-002','En el fixture nombre y firma son obligatorios; falta firma y no se puede cerrar el registro.','fixture://factory-full-source.json','Regla sintética verificable','PRIMARY','APPROVED','RESEARCH_CANDIDATE','HIGH','SYNTHETIC_STAGING_ONLY',jsonb_build_object('dataset',f,'verification','required_fields.every(nonempty) = false'),now());
insert into public.sc_creative_runs(run_key,idempotency_key,status,current_stage,trigger) values('factory-full-e2e-002','factory-full-e2e-002','APPROVED','DONE','{"synthetic":true,"verification":"fixture rule evaluated; not production agent approval"}') returning id into r;
insert into public.sc_creative_stage_outputs(run_id,stage,attempt,input_hash,schema_version,validation_status,output) values
(r,'RADAR',1,encode(extensions.digest(f::text,'sha256'),'hex'),'radar-v1','VALID',f),
(r,'EDITOR',1,encode(extensions.digest('{"candidates":[{"candidate_id":"e2e-fields","format":"image","topic":"Ejemplo sintético: no cerrar un registro sin firma requerida","caption":"Fixture de laboratorio: ambos campos son obligatorios y falta firma. No representa clientes ni datos reales.","cta":"Verificá ambos campos","plan":{"slides":[{"format":"image","layout":"paired_factors","intent":"checklist","scene":"none","theme":"cream","eyebrow":"EJEMPLO SINTÉTICO","title":"¿Listo para cerrar el registro?","body":"Cerrar exige nombre y firma. En este ejemplo falta la firma: el registro sigue pendiente.","cta":"Verificá ambos campos","items":[{"title":"Nombre presente","body":"Condición 1 cumplida: el campo tiene un valor."},{"title":"Firma ausente","body":"Condición 2 pendiente: todavía no se puede cerrar."}],"fact_ids":["SC-STAGING-CHECK-002"],"argument_key":"two_required_fields","decision_key":"do_not_close_unsigned","angle_key":"logical_and_check","hook_family":"question","added_value":"Verifica una regla AND sobre dos campos ficticios; diferencia presencia parcial de registro completo","revision":0}]}}]}'::jsonb::text,'sha256'),'hex'),'editor-v2','VALID','{"candidates":[{"candidate_id":"e2e-fields","format":"image","topic":"Ejemplo sintético: no cerrar un registro sin firma requerida","caption":"Fixture de laboratorio: ambos campos son obligatorios y falta firma. No representa clientes ni datos reales.","cta":"Verificá ambos campos","plan":{"slides":[{"format":"image","layout":"paired_factors","intent":"checklist","scene":"none","theme":"cream","eyebrow":"EJEMPLO SINTÉTICO","title":"¿Listo para cerrar el registro?","body":"Cerrar exige nombre y firma. En este ejemplo falta la firma: el registro sigue pendiente.","cta":"Verificá ambos campos","items":[{"title":"Nombre presente","body":"Condición 1 cumplida: el campo tiene un valor."},{"title":"Firma ausente","body":"Condición 2 pendiente: todavía no se puede cerrar."}],"fact_ids":["SC-STAGING-CHECK-002"],"argument_key":"two_required_fields","decision_key":"do_not_close_unsigned","angle_key":"logical_and_check","hook_family":"question","added_value":"Verifica una regla AND sobre dos campos ficticios; diferencia presencia parcial de registro completo","revision":0}]}}]}'::jsonb),
(r,'DIRECTOR',1,encode(extensions.digest('{"candidate_id":"e2e-fields","format":"image","slides":[{"template":"editorial_fact","theme":"cream","scene_key":"none"}]}'::jsonb::text,'sha256'),'hex'),'director-v2','VALID','{"candidate_id":"e2e-fields","format":"image","slides":[{"template":"editorial_fact","theme":"cream","scene_key":"none"}]}'::jsonb);
c:=public.sc_creative_compile_carousel_v1(r);
if public.sc_creative_render_preflight_v1(r)->>'ok'<>'true' then raise exception 'PREFLIGHT %',public.sc_creative_render_preflight_v1(r);end if;
insert into sc_internal.e2e_window(id,enabled,expires_at,command_id,actor,run_id,plan_hash,quality) values(true,false,now()+interval '60 minutes',extensions.gen_random_uuid(),'82029bb8-b024-40c1-ad8a-c9393b298fbf',r,sc_internal.factory_plan_hash(c),jsonb_build_object('pages',jsonb_build_array('{"format":"image","layout":"paired_factors","intent":"checklist","scene":"none","theme":"cream","eyebrow":"EJEMPLO SINTÉTICO","title":"¿Listo para cerrar el registro?","body":"Cerrar exige nombre y firma. En este ejemplo falta la firma: el registro sigue pendiente.","cta":"Verificá ambos campos","items":[{"title":"Nombre presente","body":"Condición 1 cumplida: el campo tiene un valor."},{"title":"Firma ausente","body":"Condición 2 pendiente: todavía no se puede cerrar."}],"fact_ids":["SC-STAGING-CHECK-002"],"argument_key":"two_required_fields","decision_key":"do_not_close_unsigned","angle_key":"logical_and_check","hook_family":"question","added_value":"Verifica una regla AND sobre dos campos ficticios; diferencia presencia parcial de registro completo","revision":0}'::jsonb)));
end $$;
commit;
select command_id,run_id,plan_hash,quality from sc_internal.e2e_window;
