-- Synthetic fixture, explicitly authorized; arithmetic verified in this transaction.
begin;
do $$ declare dataset jsonb:='{"id":"SC-STAGING-DATA-001","synthetic":true,"scope":"Laboratorio ficticio; no describe clientes ni resultados de Solar Connects","records":[{"id":1,"complete":true},{"id":2,"complete":true},{"id":3,"complete":true},{"id":4,"complete":true},{"id":5,"complete":true},{"id":6,"complete":true},{"id":7,"complete":true},{"id":8,"complete":true},{"id":9,"complete":true},{"id":10,"complete":false},{"id":11,"complete":false},{"id":12,"complete":false}]}'::jsonb; r uuid; c jsonb; out jsonb; total int; complete int;
begin
select count(*),count(*) filter(where (x->>'complete')::boolean) into total,complete from jsonb_array_elements(dataset->'records')x;
if total<>12 or complete<>9 or complete*100/total<>75 then raise exception 'FIXTURE_ARITHMETIC'; end if;
insert into public.sc_fact_bank(fact_id,claim,source_url,source_title,source_kind,status,authority,confidence,scope,metadata,approved_at) values('SC-STAGING-DATA-001','En el dataset sintético hay 12 registros: 9 completos (75%) y 3 pendientes.','fixture://solar-connects/staging-editorial-dataset.json','Dataset sintético versionado','PRIMARY','APPROVED','RESEARCH_CANDIDATE','HIGH','SYNTHETIC_STAGING_ONLY',jsonb_build_object('dataset',dataset,'dataset_sha256',encode(extensions.digest(dataset::text,'sha256'),'hex'),'approval_method','verified arithmetic over explicit synthetic source; not human/production approval'),now()) on conflict(fact_id) do nothing;
select id into r from public.sc_creative_runs where run_key='staging-ratio-001';
if r is null then
insert into public.sc_creative_runs(run_key,idempotency_key,status,current_stage,trigger) values('staging-ratio-001','staging-ratio-001','APPROVED','DONE','{"synthetic":true,"approval_method":"fixture contract and arithmetic validation"}') returning id into r;
insert into public.sc_creative_stage_outputs(run_id,stage,attempt,input_hash,schema_version,validation_status,output) values
(r,'RADAR',1,encode(extensions.digest(dataset::text,'sha256'),'hex'),'radar-v2','VALID',dataset),
(r,'EDITOR',1,encode(extensions.digest('{"candidates":[{"candidate_id":"staging-ratio-001","format":"image","topic":"Laboratorio sintético: completitud de un lote de doce registros","caption":"Ejercicio sintético reproducible. Nueve de doce registros completos equivalen al 75%; restan tres por revisar.","cta":"Contá, dividí y verificá","hypothesis":"Explicar porcentaje y remanente mediante datos verificables","plan":{"slides":[{"format":"image","layout":"paired_factors","intent":"checklist","scene":"none","theme":"cream","eyebrow":"LABORATORIO · DATOS SINTÉTICOS","title":"¿Cuánto falta para completar el lote?","body":"De 12 registros ficticios, 9 están completos: 75%. Revisá los 3 pendientes antes de cerrar.","cta":"Contá, dividí y verificá","items":[{"title":"9 completos","body":"9 ÷ 12 × 100 = 75%"},{"title":"3 pendientes","body":"12 − 9 = 3 por revisar"}],"fact_ids":["SC-STAGING-DATA-001"],"argument_key":"synthetic_record_completeness","decision_key":"review_three_pending","angle_key":"reproducible_ratio","hook_family":"question","added_value":"Cálculo verificable del porcentaje y del remanente en un dataset sintético de doce registros","revision":0}]}}]}'::jsonb::text,'sha256'),'hex'),'editor-v2','VALID','{"candidates":[{"candidate_id":"staging-ratio-001","format":"image","topic":"Laboratorio sintético: completitud de un lote de doce registros","caption":"Ejercicio sintético reproducible. Nueve de doce registros completos equivalen al 75%; restan tres por revisar.","cta":"Contá, dividí y verificá","hypothesis":"Explicar porcentaje y remanente mediante datos verificables","plan":{"slides":[{"format":"image","layout":"paired_factors","intent":"checklist","scene":"none","theme":"cream","eyebrow":"LABORATORIO · DATOS SINTÉTICOS","title":"¿Cuánto falta para completar el lote?","body":"De 12 registros ficticios, 9 están completos: 75%. Revisá los 3 pendientes antes de cerrar.","cta":"Contá, dividí y verificá","items":[{"title":"9 completos","body":"9 ÷ 12 × 100 = 75%"},{"title":"3 pendientes","body":"12 − 9 = 3 por revisar"}],"fact_ids":["SC-STAGING-DATA-001"],"argument_key":"synthetic_record_completeness","decision_key":"review_three_pending","angle_key":"reproducible_ratio","hook_family":"question","added_value":"Cálculo verificable del porcentaje y del remanente en un dataset sintético de doce registros","revision":0}]}}]}'::jsonb),
(r,'DIRECTOR',1,encode(extensions.digest('{"candidate_id":"staging-ratio-001","format":"image","quality_target":"QUALITY_V2","slides":[{"template":"paired_factors","theme":"cream","scene_key":"none"}]}'::jsonb::text,'sha256'),'hex'),'director-v2','VALID','{"candidate_id":"staging-ratio-001","format":"image","quality_target":"QUALITY_V2","slides":[{"template":"paired_factors","theme":"cream","scene_key":"none"}]}'::jsonb);
end if;
c:=public.sc_creative_compile_carousel_v1(r);
if c->>'ok' is distinct from 'true' then raise exception 'COMPILE_FAILED %',c;end if;
out:=public.sc_quality_factory_from_run_v2(r,jsonb_build_object('pages',jsonb_build_array('{"format":"image","layout":"paired_factors","intent":"checklist","scene":"none","theme":"cream","eyebrow":"LABORATORIO · DATOS SINTÉTICOS","title":"¿Cuánto falta para completar el lote?","body":"De 12 registros ficticios, 9 están completos: 75%. Revisá los 3 pendientes antes de cerrar.","cta":"Contá, dividí y verificá","items":[{"title":"9 completos","body":"9 ÷ 12 × 100 = 75%"},{"title":"3 pendientes","body":"12 − 9 = 3 por revisar"}],"fact_ids":["SC-STAGING-DATA-001"],"argument_key":"synthetic_record_completeness","decision_key":"review_three_pending","angle_key":"reproducible_ratio","hook_family":"question","added_value":"Cálculo verificable del porcentaje y del remanente en un dataset sintético de doce registros","revision":0}'::jsonb)),'{"enabled":true,"mode":"SHADOW","formats":["image"]}');
if out->>'ok' is distinct from 'true' then raise exception 'MATERIALIZE_FAILED %',out;end if;
insert into public.sc_system_health(component,status,details) values('staging_ready_fixture','BOUND',jsonb_build_object('synthetic',true,'run_id',r,'job_id',out->'job_id','compiled',c,'compiled_sha256',encode(extensions.digest(c::text,'sha256'),'hex'),'plan','{"format":"image","layout":"paired_factors","intent":"checklist","scene":"none","theme":"cream","eyebrow":"LABORATORIO · DATOS SINTÉTICOS","title":"¿Cuánto falta para completar el lote?","body":"De 12 registros ficticios, 9 están completos: 75%. Revisá los 3 pendientes antes de cerrar.","cta":"Contá, dividí y verificá","items":[{"title":"9 completos","body":"9 ÷ 12 × 100 = 75%"},{"title":"3 pendientes","body":"12 − 9 = 3 por revisar"}],"fact_ids":["SC-STAGING-DATA-001"],"argument_key":"synthetic_record_completeness","decision_key":"review_three_pending","angle_key":"reproducible_ratio","hook_family":"question","added_value":"Cálculo verificable del porcentaje y del remanente en un dataset sintético de doce registros","revision":0}'::jsonb)) on conflict(component) do nothing;
end $$;
commit;
select details from public.sc_system_health where component='staging_ready_fixture';
